CREATE TABLE `sys_users` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `login_name` varchar(100) NOT NULL COMMENT '登录名称',
  `name` varchar(45) DEFAULT NULL COMMENT '用户名',
  `password` varchar(45) NOT NULL COMMENT '密码',
  `nick_name` varchar(45) DEFAULT NULL COMMENT '昵称',
  `department_code` varchar(45) DEFAULT NULL COMMENT '部门code',
  `email` varchar(200) NOT NULL COMMENT 'email',
  `age` int(11) DEFAULT NULL COMMENT '年龄',
  `gender` int(11) DEFAULT '0' COMMENT '性别：0保密 1男 2女 默认0',
  `qq` varchar(45) DEFAULT NULL COMMENT 'QQ号',
  `msn` varchar(200) DEFAULT NULL COMMENT 'MSN',
  `tel` varchar(45) DEFAULT NULL COMMENT '电话号码',
  `mobile` varchar(45) DEFAULT NULL COMMENT '电话',
  `address` varchar(100) DEFAULT NULL COMMENT '地址',
  `zip_code` varchar(45) DEFAULT NULL COMMENT '邮编',
  `login_time` datetime DEFAULT NULL COMMENT '最近登录时间',
  `created_time` datetime NOT NULL COMMENT '创建时间',
  `created_by` varchar(45) DEFAULT NULL COMMENT '创建人',
  `modified_time` datetime NOT NULL COMMENT '最近修改时间',
  `modified_by` varchar(45) DEFAULT NULL COMMENT '修改人',
  `status` int(11) NOT NULL DEFAULT '1' COMMENT '删除状态：0 删除 1 未删除',
  PRIMARY KEY (`id`) COMMENT '用户表'
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;
